# Generated by Django 5.1 on 2024-11-26 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchedlist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('year', models.DateField()),
                ('type', models.CharField(max_length=10)),
                ('description', models.TextField(max_length=1000)),
                ('rate', models.IntegerField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], null=True)),
                ('list', models.CharField(choices=[('watchlist', 'watchlist'), ('watchedlist', 'watchedlist'), ('droppedlist', 'droppedlist')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lister', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
