# Generated by Django 5.1 on 2025-01-02 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchedlist', '0002_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='description',
            new_name='comment',
        ),
    ]
