# Generated by Django 5.1 on 2025-01-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchedlist', '0003_rename_description_item_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
