# Generated by Django 5.1 on 2025-01-09 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchedlist', '0005_item_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='year',
        ),
    ]
